spring:
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: always
      schema-locations: classpath:scripts/schema.sql, classpath*:scripts/ddl.sql
      data-locations: classpath*:scripts/data*.sql